services:
  - type: web
    plan: free
    name: proffesorbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/maihuyar/kissum
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: CHANNELS
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUPPORT_CHAT
        sync: false
      - key: ADMINS 
        sync: false
